ALTER TABLE tasks ADD COLUMN usage_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN usage_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE node_runs ADD COLUMN usage_tokens INTEGER NOT NULL DEFAULT 0;
